---
title: "README.md"
author: "EA"
date: "September 7, 2018"
output: 
  md_document:
    variant: markdown_github
        
---

#### Lesson 6 - Linear Regression, Multiple Linear Regression, ANOVA, ANCOVA: Choosing the Best Model for the Job

(The entire Lesson 6 folder can be downloaded [here](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/eacton/CAGEF/tree/master/Lesson_6) thanks to DownGit)

__Objective:__ At the end of this session you will be able to perform simple and multiple linear regression, one- and multiway analysis of variance (ANOVA) and analysis of covariance (ANCOVA). You will be able to interpret the statistics that come out of this model, be cognizant of the assumptions the model makes, and use an F-test to select the best model for the job. 


_How we Evaluate which Model to Use_

- How do we describe our data?
- What hypotheses are we testing?
- What assumptions does our model have?
- How do we test these assumptions?
- How do we compare models?
- How do we interpret the output of our model?
- How do we make a prediction for new values?
 

_Models we will Consider_

- T-tests
- Simple linear regression
- Multiple linear regression
- One- and Multi-way Analysis of Variance (ANOVA)
- Analysis of Covariance (ANCOVA)

_Assumptions of general linear models_

- normality
- independence
- equal variance
- linearity


_Important considerations_

- Dummy variables: encoding categorical variables
- Interaction terms
- Multiple test correction

_Resources_

- Prediction
    + confidence vs prediction (narrow vs wide) intervals
- Assessing the performance of the model (feedback)
    + Checking residuals
    + Q-Q plots
    + Next steps (when assumptions fail)