---
title: "README.md"
author: "EA"
date: "September 7, 2018"
output: 
  md_document:
    variant: markdown_github
        
---

#### Lesson 2 - Basic Life Skills: How to Read, Write, and Manipulate (Your Data)

(The entire Lesson 2 folder can be downloaded [here](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/eacton/CAGEF/tree/master/Lesson_2) thanks to DownGit)

__Objective:__ At the end of this session you will be able to use the dplyr package to subset and manipulate your data and to perform simple calculations. You will be able to import data into R (tsv, csv, xls(x), googlesheets) and export your data again.


_Reading in and writing data_

- get your csv, tsv, xls(x) and googlesheets data into and out of R
- determine the default arguments in help files


_Data Manipulation_     

- the dplyr package: 
      + how to subset data with filter(), select()
      + how to order data with arrange()
      + using mutate(), transmute() for new data columns 
      + using summarize() to get mean, median, modes, quantiles and standard deviations
      + using group_by() to perform calculations on factored data 
      + use select 'helpers' to grab specific columns
      
