---
title: "Lesson 3 - Plot all the things! From Data Exploration to Publication-Quality Figures"
output: 
  html_document:
          keep_md: yes
          toc: TRUE
          toc_depth: 3
  html_notebook:
          toc: TRUE
          toc_depth: 3
---
***

Approximate time: 2 hours per lesson

 _Each lesson will have:_
 
 - Comprehension questions as we go along on Socrative.
 - How to read help pages online.
 - Give the class a function not previously used during the lesson and have them figure out what it does and how to use it.
 - Each lesson will start from an excel spreadsheet with imperfect data.

***
__Objective:__ At the end of this session you will be able to use ggplot2() to make a ton of different types of plots with your data for both for data exploration and for publication-quality figures.   

_Intro to the Grammar of Graphics_

- general structure of ggplot2 syntax()
- dependence of ggplot2 on the tidy data format

_Data Exploration - plot all the things!_

- dot plots, line graphs, scatter plots, bar graphs, violin plots, histograms, facetting
- emphasis on boxplots + explanation, beeswarm plots
- heatmaps and correlation plots
  
_Making Figures_

- labels, scaling, ggsave(), regression lines, error bars, changing axis limits, rotating labels, adding text to data points, changing the legend, alpha, colors, shapes
- forcats pkg: controlling categorical variable order in your legend
- alternatives to pie charts
- customize with ggthemes
  
_Taking it up a notch_ - Maybe preview these, and if time vote on one to look at in more detail

- Interactive graphics (d3heatmap, ggvis, plotly)
- Network diagrams (DiagrammR, igraph)
- dygraphs() - time series data, migest - circos plots
- upset plots
- geospatial data? interest?
- phylogenetics data - ggtree, treeman, metacoder
- genomics data - ggbio
   
__Challenge:__ 

Take one of the provided test sets (cars, iris, gapminder, lotr, game of thrones, air quality) and plot: 

  1. a qualitative variable with a quantitative variable (at least 2 ways). 
    + Facet your plot by the qualitative variable.
  2. two quantitative variables (at least 2 ways). 
    + Add a regression line to your plot.

__Resources:__     
https://github.com/jennybc/ggplot2-tutorial
    

##Post-Lesson Assessment
***
_Questions_

- Speed: Too slow, too fast, just right
- Content: Too easy, too hard, just right
- From the description of the lesson, the content was what I expected to learn. T/F
- What was the most useful thing you learned?
- What was the least useful thing?
- Comments/suggestions for improvement.


##Notes
***
- Maybe switch Regex and Plotting lesson order