---
title: "Lesson 6 - Scaling up your Analyses: Writing Functions in R"
output: 
  html_document:
          keep_md: yes
          toc: TRUE
          toc_depth: 3
  html_notebook:
          toc: TRUE
          toc_depth: 3
---
***

Approximate time: 2 hours per lesson

 _Each lesson will have:_
 
 - Comprehension questions as we go along on Socrative.
 - How to read help pages online.
 - Give the class a function not previously used during the lesson and have them figure out what it does and how to use it.
 - Each lesson will start from an excel spreadsheet with imperfect data.

***
__Objective:__ At the end of this session you will be able to write functions, making your coding more efficient, understandable, reproducible, and hopefully less frustrating.


_Basic Syntax of Functions in R_

- the structure of a function
- understanding scoping
- naming conventions
- adding '...'
- the output of your function
- sourcing functions
  
_Handling Errors_

- stopifnot(), warning(), suppressWarnings(), tryCatch()

_Testing Arguments and Validity of your Function_

- testthat() for formal unit testing


__Challenge:__

1. Write a function to check that the packages c("dplyr", "readxml", "tidyr") are installed and to load the packages. The function should install the packages if they are not already installled. Write a warning if the package is not installed, but is being installed. Will this function work for other packages? 

2. Write a function to read all .csv files in a directory into R and save each of them in a separate data frame.

__Resources:__ 

http://stat545.com/block011_write-your-own-function-01.html     
http://stat545.com/block011_write-your-own-function-02.html     
http://stat545.com/block011_write-your-own-function-03.html     
http://mazamascience.com/WorkingWithData/?p=912


##Post-Lesson Assessment
***
_Questions_

- Speed: Too slow, too fast, just right
- Content: Too easy, too hard, just right
- From the description of the lesson, the content was what I expected to learn. T/F
- What was the most useful thing you learned?
- What was the least useful thing?
- Comments/suggestions for improvement.


##Notes
***
- Possibly split lesson 5 into 2 lessons: Basic Statistics and Linear regression
- Maybe switch Regex and Plotting lesson order