---
title: "Lesson 5 - Linear and Non-Linear Regression: Choosing the Best Model for the Job"
output: 
  html_document:
          keep_md: yes
          toc: TRUE
          toc_depth: 3
  html_notebook:
          toc: TRUE
          toc_depth: 3
---
***

Approximate time: 2 hours per lesson

 _Each lesson will have:_
 
 - Comprehension questions as we go along on Socrative.
 - How to read help pages online.
 - Give the class a function not previously used during the lesson and have them figure out what it does and how to use it.
 - Each lesson will start from an excel spreadsheet with imperfect data.


***
__Objective:__ At the end of this session you will be able to perform simple and multiple linear or non-linear regression on your dataset. You will be able to interpret the statistics that come out of this model, and use these statistics to select the best model for the job. 

_Commonly used statistics_

- quick review: mean, median, mode, quantiles, sd, variance     
- t-tests     
- correlations     
- explain parametric vs non-parametric data     

_Models we will Consider_

- Simple linear regression
- Non-linear regression
- Multiple linear regression
- ANOVA

_How we Evaluate which Model to Use_

- Taking a moment to think about the question we are asking...
- Assumptions of the model
- Interpreting the output of our model
- Assessing the performance of the model (feedback)
    + Diagnostic plots (ie. residuals, Q-Q plots)


_Running the Model_

- Dealing with dummy variables/encoding categorical variables
- Is it necessary to scale our data?
- Using broom() to get a data frame of our result statistics
- Predictors 

__Challenge:__      

Given this dataset, answer this question. Is this the best model for the job? What else could you apply? Can you prove this is any better?

__Resources:__      
https://github.com/ttimbers/lm_and_glm/blob/master/lm_and_glm.Rmd     
https://github.com/seananderson/glmm-course     
http://michael.hahsler.net/SMU/EMIS7331/R/regression.html
    


##Post-Lesson Assessment
***
_Questions_

- Speed: Too slow, too fast, just right
- Content: Too easy, too hard, just right
- From the description of the lesson, the content was what I expected to learn. T/F
- What was the most useful thing you learned?
- What was the least useful thing?
- Comments/suggestions for improvement.


##Notes
***
- Possibly split lesson 5 into 2 lessons: Basic Statistics and Linear regression
- Maybe switch Regex and Plotting lesson order